# Generated by Django 4.0.4 on 2022-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('Waiter', 'Waiter'), ('Chef', 'Chef'), ('Admin', 'Admin')], max_length=200),
        ),
    ]
